create table if not exists api_usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  provider text not null,
  model text,
  model_label text,
  tokens integer not null default 0,
  tokens_per_eur integer not null default 100,
  cost_eur numeric(10, 2) not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists api_usage_events_created_at_idx
  on api_usage_events (created_at);

create index if not exists api_usage_events_model_idx
  on api_usage_events (model_label, model);

create index if not exists api_usage_events_provider_idx
  on api_usage_events (provider);

