create table if not exists billing_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  provider text not null,
  event_type text not null,
  provider_payment_id text not null,
  amount_eur numeric(10, 2) not null default 0,
  currency text not null default 'EUR',
  paid_at timestamptz not null,
  created_at timestamptz not null default now(),
  metadata jsonb
);

create unique index if not exists billing_events_provider_payment_key
  on billing_events (provider, provider_payment_id);

create index if not exists billing_events_paid_at_idx
  on billing_events (paid_at);

create index if not exists billing_events_user_id_idx
  on billing_events (user_id);
